name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
          check-latest: true
      - name: Go vendor
        run: for d in common pwlib .; do cd $d; go mod tidy; go mod vendor; cd -; done
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
          check-latest: true
      - name: Go mod tidy
        run: go mod tidy
      - name: Go Vendor
        run: go mod vendor
      - name: Install dependencies
        run: go get .
      - uses: "golangci/golangci-lint-action@v3.3.1"