name: Go pwlib

on: [push]

jobs:
  build:
    defaults:
      run:
        working-directory: pwlib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
          check-latest: true
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

  lint:
    defaults:
      run:
        working-directory: pwlib
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          check-latest: true
      - uses: "golangci/golangci-lint-action@v3"